
runtime: python39
entrypoint: gunicorn -b :$PORT first_project.wsgi:application

env_variables:
  DJANGO_SETTINGS_MODULE: "first_project.settings"
  APPENGINE_URL: https://coral-smoke-411614.uc.r.appspot.com

handlers:
- url: /static
  static_dir: static/
- url: /media
  static_dir: media/
- url: /.*
  script: autoy

    
